-- MySQL Script generated by MySQL Workbench
-- Mon Jul 13 16:40:34 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema finora_br
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema finora_br
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `finora_br` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `finora_br` ;

-- -----------------------------------------------------
-- Table `finora_br`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finora_br`.`users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_username_unique` (`username` ASC) VISIBLE,
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `finora_br`.`payment_methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finora_br`.`payment_methods` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `balance` DECIMAL(14,2) NOT NULL DEFAULT '0.00',
  `is_favorite` TINYINT(1) NOT NULL DEFAULT '0',
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `payment_methods_user_id_is_active_index` (`user_id` ASC, `is_active` ASC) VISIBLE,
  CONSTRAINT `payment_methods_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `finora_br`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `finora_br`.`invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finora_br`.`invoices` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `payment_method_id` BIGINT UNSIGNED NOT NULL,
  `reference_year` SMALLINT UNSIGNED NOT NULL,
  `reference_month` TINYINT UNSIGNED NOT NULL,
  `cycle` SMALLINT UNSIGNED NOT NULL DEFAULT '1',
  `status` ENUM('open', 'paid') NOT NULL DEFAULT 'open',
  `paid_at` TIMESTAMP NULL DEFAULT NULL,
  `paid_from_payment_method_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `payment_expense_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `invoices_user_card_reference_cycle_unique` (`user_id` ASC, `payment_method_id` ASC, `reference_year` ASC, `reference_month` ASC, `cycle` ASC) VISIBLE,
  INDEX `invoices_payment_method_id_foreign` (`payment_method_id` ASC) VISIBLE,
  INDEX `invoices_paid_from_payment_method_id_foreign` (`paid_from_payment_method_id` ASC) VISIBLE,
  INDEX `invoices_user_id_status_reference_year_reference_month_index` (`user_id` ASC, `status` ASC, `reference_year` ASC, `reference_month` ASC) VISIBLE,
  INDEX `invoices_user_card_reference_status_index` (`user_id` ASC, `payment_method_id` ASC, `reference_year` ASC, `reference_month` ASC, `status` ASC) VISIBLE,
  CONSTRAINT `invoices_paid_from_payment_method_id_foreign`
    FOREIGN KEY (`paid_from_payment_method_id`)
    REFERENCES `finora_br`.`payment_methods` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `invoices_payment_method_id_foreign`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `finora_br`.`payment_methods` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `invoices_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `finora_br`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `finora_br`.`expenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finora_br`.`expenses` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `payment_method_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `destination_payment_method_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `invoice_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `description` VARCHAR(255) NOT NULL,
  `amount` DECIMAL(14,2) NOT NULL,
  `transaction_date` DATE NOT NULL,
  `type` ENUM('credit', 'debit', 'deposit', 'transfer', 'boleto', 'invoice_payment') NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `expenses_payment_method_id_foreign` (`payment_method_id` ASC) VISIBLE,
  INDEX `expenses_destination_payment_method_id_foreign` (`destination_payment_method_id` ASC) VISIBLE,
  INDEX `expenses_user_id_transaction_date_index` (`user_id` ASC, `transaction_date` ASC) VISIBLE,
  INDEX `expenses_user_id_type_index` (`user_id` ASC, `type` ASC) VISIBLE,
  INDEX `expenses_invoice_id_type_index` (`invoice_id` ASC, `type` ASC) VISIBLE,
  CONSTRAINT `expenses_destination_payment_method_id_foreign`
    FOREIGN KEY (`destination_payment_method_id`)
    REFERENCES `finora_br`.`payment_methods` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `expenses_invoice_id_foreign`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `finora_br`.`invoices` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `expenses_payment_method_id_foreign`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `finora_br`.`payment_methods` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `expenses_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `finora_br`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `finora_br`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finora_br`.`migrations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `finora_br`.`personal_access_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `finora_br`.`personal_access_tokens` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tokenable_type` VARCHAR(255) NOT NULL,
  `tokenable_id` BIGINT UNSIGNED NOT NULL,
  `name` TEXT NOT NULL,
  `token` VARCHAR(64) NOT NULL,
  `abilities` TEXT NULL DEFAULT NULL,
  `last_used_at` TIMESTAMP NULL DEFAULT NULL,
  `expires_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `personal_access_tokens_token_unique` (`token` ASC) VISIBLE,
  INDEX `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type` ASC, `tokenable_id` ASC) VISIBLE,
  INDEX `personal_access_tokens_expires_at_index` (`expires_at` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
